// Tune Up beta — Georgian strings. Keys are the English texts used in t(). Keep entries short and natural.
export const KA = {
  'Tbilisi': 'თბილისი',
  'closed beta': 'დახურული ბეტა',
  'Your coach, in your pocket every day.': 'შენი მწვრთნელი — ყოველდღე, შენს ჯიბეში.',
  'Continue with e-mail': 'გაგრძელება ელფოსტით',
  'No passwords — we e-mail you a one-time code.': 'პაროლის გარეშე — ელფოსტაზე ერთჯერად კოდს გამოგიგზავნით.',
  'Invitation': 'მოწვევა',
  '{name} invited you to Tune Up': '{name} გიწვევს Tune Up-ში',
  'Your coach': 'შენი მწვრთნელი',
  'Sign in with your e-mail to accept.': 'მოწვევის მისაღებად შედი ელფოსტით.',
  'You are invited as a coach': 'მოწვეული ხარ როგორც მწვრთნელი',
  'Sign in with your e-mail to set up your coach account.': 'მწვრთნელის ანგარიშის შესაქმნელად შედი ელფოსტით.',
  'This invite link is no longer valid': 'ეს მოწვევის ბმული აღარ მუშაობს',
  'Ask for a new link. You can still sign in if you already have an account.': 'ითხოვე ახალი ბმული. თუ ანგარიში უკვე გაქვს, შესვლა მაინც შეგიძლია.',
  'The beta is not switched on yet. Check back soon.': 'ბეტა ჯერ ჩართული არ არის. მალე დაბრუნდი.',
  'Sign in': 'შესვლა',
  'Enter your e-mail. We will send you a one-time code.': 'ჩაწერე ელფოსტა. ერთჯერად კოდს გამოგიგზავნით.',
  'E-mail': 'ელფოსტა',
  'Send code': 'კოდის გაგზავნა',
  'Please enter a valid e-mail.': 'ჩაწერე სწორი ელფოსტა.',
  'Too many attempts — wait a minute and try again.': 'ძალიან ბევრი მცდელობა — დაიცადე ერთი წუთი და სცადე თავიდან.',
  'Could not send the code. Check the e-mail and try again.': 'კოდი ვერ გაიგზავნა. შეამოწმე ელფოსტა და სცადე თავიდან.',
  'Check your e-mail': 'შეამოწმე ელფოსტა',
  'We sent a code to {email}. Type all its digits here.': 'კოდი გავაგზავნეთ {email}-ზე. ჩაწერე ყველა ციფრი.',
  'No e-mail? Check spam, or': 'წერილი არ მოვიდა? შეამოწმე სპამი, ან',
  'send it again': 'გაგზავნე თავიდან',
  'Enter the code from the e-mail.': 'ჩაწერე წერილში მოსული კოდი.',
  'That code did not work. Check it or request a new one.': 'ეს კოდი არ გამოვიდა. შეამოწმე ან ითხოვე ახალი.',
  'Code sent again': 'კოდი თავიდან გაიგზავნა',
  'Could not send — wait a minute': 'ვერ გაიგზავნა — დაიცადე ერთი წუთი',
  'Before we start': 'სანამ დავიწყებთ',
  'Your data': 'შენი მონაცემები',
  'Tune Up stores what you and your coach enter: name, e-mail, weight, goals, injuries, food and training logs, check-ins and messages. Some of this is health-related data.': 'Tune Up ინახავს იმას, რასაც შენ და შენი მწვრთნელი შეიყვანთ: სახელი, ელფოსტა, წონა, მიზნები, ტრავმები, კვებისა და ვარჯიშის ჩანაწერები, დღის შეფასებები და შეტყობინებები. ამის ნაწილი ჯანმრთელობასთან დაკავშირებული მონაცემია.',
  'It is kept on servers in the EU (Frankfurt), shown only to you, your coach and the Tune Up team, and never sold or shared with anyone else.': 'ინახება ევროკავშირის სერვერებზე (ფრანკფურტი), ხედავთ მხოლოდ შენ, შენი მწვრთნელი და Tune Up-ის გუნდი; არასდროს იყიდება და სხვას არ გადაეცემა.',
  'You can delete your account and all of its data at any time from More → Delete account.': 'ანგარიშისა და ყველა მონაცემის წაშლა ნებისმიერ დროს შეგიძლია: მეტი → ანგარიშის წაშლა.',
  'This is a free closed beta: things may change or break, and we may ask you for feedback.': 'ეს უფასო დახურული ბეტაა: რაღაცები შეიძლება შეიცვალოს ან გაფუჭდეს, და შეიძლება აზრი გკითხოთ.',
  'I agree — continue': 'ვეთანხმები — გაგრძელება',
  'Not now — sign out': 'ახლა არა — გასვლა',
  'Something went wrong — try again': 'რაღაც არასწორად წავიდა — სცადე თავიდან',
  'Something went wrong — try again.': 'რაღაც არასწორად წავიდა — სცადე თავიდან.',
  'Invite only': 'მხოლოდ მოწვევით',
  'Tune Up is invite-only during the beta': 'ბეტის დროს Tune Up მხოლოდ მოწვევით მუშაობს',
  'Ask your coach for an invite link and open it on this phone. If you are a coach, ask the Tune Up team for your link.': 'სთხოვე მწვრთნელს მოწვევის ბმული და გახსენი ამ ტელეფონზე. თუ მწვრთნელი ხარ, ბმულს Tune Up-ის გუნდი მოგცემს.',
  'Signed in as {email}': 'შესული ხარ როგორც {email}',
  'Sign out': 'გასვლა',
  'Account paused': 'ანგარიში შეჩერებულია',
  'This account has been paused by the Tune Up team.': 'ეს ანგარიში Tune Up-ის გუნდმა შეაჩერა.',
  'Contact us if you think this is a mistake.': 'თუ ფიქრობ, რომ ეს შეცდომაა, დაგვიკავშირდი.',
  'Delete your account?': 'წავშალოთ ანგარიში?',
  'This removes your profile, logs, messages and pairing for good. It cannot be undone.': 'ეს სამუდამოდ წაშლის შენს პროფილს, ჩანაწერებს, შეტყობინებებს და მწვრთნელთან კავშირს. უკან დაბრუნება შეუძლებელია.',
  'Delete everything': 'ყველაფრის წაშლა',
  'Keep my account': 'ანგარიშის დატოვება',
  'Account deleted': 'ანგარიში წაიშალა',
  'Could not delete — try again': 'ვერ წაიშალა — სცადე თავიდან',
  // onboarding
  'Set up your coach profile': 'შექმენი მწვრთნელის პროფილი',
  'Clients see this when they join you. Keep it short — you can edit it later.': 'ამას კლიენტები შემოერთებისას დაინახავენ. მოკლედ — მერე შეცვლა შეგიძლია.',
  'Your name': 'შენი სახელი',
  'e.g. Giorgi Kapanadze': 'მაგ. გიორგი კაპანაძე',
  'What you coach': 'რას ავარჯიშებ',
  'One line about you': 'ერთი წინადადება შენზე',
  'e.g. 8 years of strength coaching, calm and consistent.': 'მაგ. 8 წელი ძალისმიერ ვარჯიშში, მშვიდი და თანმიმდევრული.',
  'Gym': 'დარბაზი',
  'e.g. Fitness One, Saburtalo': 'მაგ. Fitness One, საბურთალო',
  'District': 'უბანი',
  'e.g. Vake': 'მაგ. ვაკე',
  'How you train clients': 'როგორ ავარჯიშებ კლიენტებს',
  'Create coach account': 'მწვრთნელის ანგარიშის შექმნა',
  'Please enter your name.': 'ჩაწერე სახელი.',
  'Welcome, coach': 'კეთილი იყოს შენი მობრძანება, მწვრთნელო',
  'Join {name}': 'შეუერთდი {name}-ს',
  'your coach': 'შენი მწვრთნელი',
  'A few answers so {name} can plan for you. Everything here is only visible to you and your coach.': 'რამდენიმე პასუხი, რომ {name}-მა შენთვის დაგეგმოს. ამას მხოლოდ შენ და შენი მწვრთნელი ხედავთ.',
  'e.g. Nino Beridze': 'მაგ. ნინო ბერიძე',
  'Weight': 'წონა',
  'Height': 'სიმაღლე',
  'Experience': 'გამოცდილება',
  'Main goal': 'მთავარი მიზანი',
  'Anything specific?': 'რამე კონკრეტული?',
  'e.g. lose 5 kg before summer, run 5 km': 'მაგ. ზაფხულამდე 5 კგ დაკლება, 5 კმ სირბილი',
  'Injuries or limits': 'ტრავმები ან შეზღუდვები',
  'e.g. left knee, lower back — or none': 'მაგ. მარცხენა მუხლი, წელი — ან არაფერი',
  'Diet': 'კვება',
  'e.g. no restrictions, vegetarian, fasting': 'მაგ. შეზღუდვების გარეშე, ვეგეტარიანელი, მარხვა',
  'How you want to train': 'როგორ გინდა ვარჯიში',
  'Join and start': 'შეერთება და დაწყება',
  'Pick your experience and main goal.': 'აირჩიე გამოცდილება და მთავარი მიზანი.',
  'You are paired': 'მწვრთნელს დაუკავშირდი',
  'This invite link is no longer valid — ask for a new one.': 'ეს მოწვევის ბმული აღარ მუშაობს — ითხოვე ახალი.',
  'You already have a coach. Ask them to end the pairing first.': 'მწვრთნელი უკვე გყავს. ჯერ სთხოვე კავშირის დასრულება.',
  'This account is already set up in another role.': 'ეს ანგარიში უკვე სხვა როლშია.',
  'You cannot use your own invite link.': 'საკუთარ მოწვევის ბმულს ვერ გამოიყენებ.',
  'Please accept the data notice first.': 'ჯერ დაეთანხმე მონაცემების შეტყობინებას.',
  'You already have a coach': 'მწვრთნელი უკვე გყავს',
  'Profile not ready — try again': 'პროფილი ჯერ მზად არ არის — სცადე თავიდან',
  'Could not load your data — pull to refresh or sign in again': 'მონაცემები ვერ ჩაიტვირთა — განაახლე გვერდი ან შედი თავიდან',
  // options
  'Beginner': 'დამწყები', 'Some experience': 'ცოტა გამოცდილება', 'Train regularly': 'რეგულარულად ვვარჯიშობ',
  'Lose fat': 'ცხიმის დაკლება', 'Build muscle': 'კუნთის მომატება', 'Get fit and toned': 'ფორმაში მოსვლა', 'Health and energy': 'ჯანმრთელობა და ენერგია', 'Sport performance': 'სპორტული შედეგი',
  'In person': 'პირისპირ', 'Online': 'ონლაინ', 'In person or online': 'პირისპირ ან ონლაინ',
  'Strength': 'ძალა', 'Fat loss': 'ცხიმის დაკლება', 'Muscle': 'კუნთი', 'Mobility': 'მოძრაობა', 'Running': 'სირბილი', 'After injury': 'ტრავმის შემდეგ', 'Women’s fitness': 'ქალთა ფიტნესი', '50+': '50+',
  'Trainee': 'მოვარჯიშე', 'Coach': 'მწვრთნელი', 'Admin': 'ადმინი', 'No role': 'როლის გარეშე',
  // tabs
  'Today': 'დღეს', 'More': 'მეტი', 'Clients': 'კლიენტები', 'Invites': 'მოწვევები', 'Overview': 'მიმოხილვა', 'Coaches': 'მწვრთნელები', 'Users': 'მომხმარებლები',
  // trainee
  'Hi, {name}': 'გამარჯობა, {name}',
  'You are paired with {name}': 'შენი მწვრთნელია {name}',
  'Your weekly plan, targets and check-ins will appear here as soon as your coach sets them up.': 'კვირის გეგმა, მიზნები და დღის შეფასებები აქ გამოჩნდება, როგორც კი მწვრთნელი მოამზადებს.',
  'Your coaching with {name} has ended': '{name}-თან ვარჯიში დასრულდა',
  'No coach yet': 'მწვრთნელი ჯერ არ გყავს',
  'Open a new invite link from a coach to start again.': 'თავიდან დასაწყებად გახსენი მწვრთნელის ახალი მოწვევის ბმული.',
  'Together since {date}': 'ერთად {date}-დან',
  'Language': 'ენა',
  'My answers': 'ჩემი პასუხები',
  'Weight, goal, injuries, diet': 'წონა, მიზანი, ტრავმები, კვება',
  'Delete account': 'ანგარიშის წაშლა',
  'Removes all your data': 'წაშლის ყველა შენს მონაცემს',
  'Editing comes next week — for now tell your coach about changes.': 'რედაქტირება მომავალ კვირას დაემატება — ცვლილებები ჯერ მწვრთნელს უთხარი.',
  // coach
  '{n} active': '{n} აქტიური',
  'No clients yet': 'კლიენტები ჯერ არ გყავს',
  'Create an invite link and send it to a client. They sign up through it and land here.': 'შექმენი მოწვევის ბმული და გაუგზავნე კლიენტს. ის ამ ბმულით დარეგისტრირდება და აქ გამოჩნდება.',
  'Invite a client': 'კლიენტის მოწვევა',
  'Ended': 'დასრულებული',
  'Ended {date}': 'დასრულდა {date}',
  'Not found': 'ვერ მოიძებნა',
  'How they want to train': 'როგორ უნდა ვარჯიში',
  'Plan, targets and check-ins': 'გეგმა, მიზნები და დღის შეფასებები',
  'The plan builder arrives next week. For now you can review their answers.': 'გეგმის შედგენა მომავალ კვირას დაემატება. ჯერ პასუხების ნახვა შეგიძლია.',
  'End coaching': 'ვარჯიშის დასრულება',
  'End coaching with {name}?': 'დავასრულოთ ვარჯიში {name}-თან?',
  'They will see that the coaching ended, with your note. Their data stays with them.': 'ის დაინახავს, რომ ვარჯიში დასრულდა, შენი შენიშვნით. მისი მონაცემები მას რჩება.',
  'Short note (optional)': 'მოკლე შენიშვნა (არასავალდებულო)',
  'e.g. Thank you — you reached your goal!': 'მაგ. მადლობა — მიზანს მიაღწიე!',
  'Cancel': 'გაუქმება',
  'Coaching ended': 'ვარჯიში დასრულდა',
  'Could not end — try again': 'ვერ დასრულდა — სცადე თავიდან',
  'Note': 'შენიშვნა',
  'Invite links': 'მოწვევის ბმულები',
  'One link per client': 'ერთი ბმული — ერთი კლიენტი',
  'Send the link in any messenger. When the client opens it and signs up, they are paired with you.': 'გაუგზავნე ბმული ნებისმიერ მესენჯერში. როცა კლიენტი გახსნის და დარეგისტრირდება, შენთან დაუკავშირდება.',
  'New invite link': 'ახალი მოწვევის ბმული',
  'Waiting': 'ელოდება',
  'Used': 'გამოყენებული',
  'Used {date}': 'გამოყენებულია {date}',
  'Valid until {date}': 'მოქმედებს {date}-მდე',
  'Invite': 'მოწვევა',
  'Who is it for? (only you see this)': 'ვისთვისაა? (ამას მხოლოდ შენ ხედავ)',
  'e.g. Nino': 'მაგ. ნინო',
  'Create link': 'ბმულის შექმნა',
  'Could not create — try again': 'ვერ შეიქმნა — სცადე თავიდან',
  'Invite link': 'მოწვევის ბმული',
  'Hi! Join me on Tune Up — open this link on your phone and sign up: {link}': 'გამარჯობა! შემოუერთდი Tune Up-ს — გახსენი ეს ბმული ტელეფონზე და დარეგისტრირდი: {link}',
  'Works once, for 30 days. Send it to the client only.': 'მუშაობს ერთხელ, 30 დღის განმავლობაში. გაუგზავნე მხოლოდ კლიენტს.',
  'Copy': 'კოპირება', 'Send': 'გაგზავნა', 'Done': 'მზადაა', 'Copied': 'დაკოპირდა',
  'Select and copy the link': 'მონიშნე და დააკოპირე ბმული',
  'Coach profile': 'მწვრთნელის პროფილი',
  'Gym, district, what you coach': 'დარბაზი, უბანი, რას ავარჯიშებ',
  'Save': 'შენახვა', 'Saved': 'შენახულია',
  'Could not save — try again': 'ვერ შეინახა — სცადე თავიდან',
  // week 2: plan, library, targets, goals, workout
  'Plan': 'გეგმა', 'Weekly plan': 'კვირის გეგმა', 'Rest day': 'დასვენების დღე', 'today': 'დღეს', 'from {name}': '{name}-სგან',
  '1 exercise': '1 ვარჯიში', '{n} exercises': '{n} ვარჯიში',
  'Today\'s workout': 'დღევანდელი ვარჯიში', 'Workout done — nice work!': 'ვარჯიში შესრულებულია — ყოჩაღ!',
  'Nothing planned for today — recover well.': 'დღეს არაფერია დაგეგმილი — კარგად დაისვენე.',
  'No plan yet': 'გეგმა ჯერ არ არის',
  'Daily targets': 'დღიური მიზნები', 'Not set yet': 'ჯერ არ არის დაყენებული', 'Leave empty what you do not track.': 'რასაც არ ითვლი, ცარიელი დატოვე.',
  'Calories': 'კალორიები', 'Protein': 'ცილა', 'Water': 'წყალი', 'Steps': 'ნაბიჯები', 'protein': 'ცილა', 'water': 'წყალი', 'steps': 'ნაბიჯი',
  'Logging food, water and steps arrives next week.': 'კვების, წყლისა და ნაბიჯების ჩაწერა მომავალ კვირას დაემატება.',
  'Could not save — check the numbers': 'ვერ შეინახა — შეამოწმე რიცხვები',
  'Goals': 'მიზნები', 'No goals yet': 'მიზნები ჯერ არ არის', 'New goal': 'ახალი მიზანი', 'Add goal': 'მიზნის დამატება',
  'Edit': 'რედაქტირება', 'Their answers': 'მისი პასუხები', 'Injuries': 'ტრავმები', 'Loading the plan…': 'გეგმა იტვირთება…', 'Could not load the plan': 'გეგმა ვერ ჩაიტვირთა',
  'Add exercise': 'ვარჯიშის დამატება', 'Add to {day}': 'დამატება: {day}', 'Add to plan': 'გეგმაში დამატება', 'Added': 'დაემატა',
  'Rest day — add an exercise to make it a training day': 'დასვენების დღე — დაამატე ვარჯიში და გახდება საწვრთნელი დღე',
  'Search exercises': 'ვარჯიშების ძებნა', 'Library': 'ბიბლიოთეკა', 'My exercises': 'ჩემი ვარჯიშები', 'Nothing found': 'ვერაფერი მოიძებნა',
  'New exercise with my video link': 'ახალი ვარჯიში ჩემი ვიდეოს ბმულით', 'New exercise': 'ახალი ვარჯიში', 'Save exercise': 'ვარჯიშის შენახვა',
  'Name': 'სახელი', 'Muscle group': 'კუნთების ჯგუფი', 'Video link (YouTube, Drive…)': 'ვიდეოს ბმული (YouTube, Drive…)', 'optional': 'არასავალდებულო',
  'e.g. Box squat (my cue)': 'მაგ. ბოქს სქვოთი (ჩემი ვერსია)', 'e.g. Legs': 'მაგ. ფეხები',
  'Please enter a name.': 'ჩაწერე სახელი.', 'The video link must start with https://': 'ვიდეოს ბმული https://-ით უნდა იწყებოდეს',
  'Your own moves and video links': 'შენი ვარჯიშები და ვიდეოს ბმულები', 'Your own moves and video links. Clients see them inside their plan.': 'შენი ვარჯიშები და ვიდეოს ბმულები. კლიენტები მათ გეგმაში ხედავენ.',
  'None yet.': 'ჯერ არაფერია.', 'Removed': 'წაიშალა', 'Could not remove — it may be in a plan': 'ვერ წაიშალა — შეიძლება გეგმაშია',
  'Could not remove — try again': 'ვერ წაიშალა — სცადე თავიდან', 'Could not add — try again': 'ვერ დაემატა — სცადე თავიდან',
  'Sets': 'სეტი', 'Reps': 'გამეორება', 'Load': 'წონა', 'Note for the client': 'შენიშვნა კლიენტისთვის',
  'e.g. 20 kg, bodyweight': 'მაგ. 20 კგ, საკუთარი წონით', 'e.g. slow on the way down': 'მაგ. ნელა დაშვებისას',
  'Remove from this day': 'ამ დღიდან წაშლა', 'Video': 'ვიდეო', 'video': 'ვიდეო',
  // admin
  'Active pairs': 'აქტიური წყვილები', 'Trainees': 'მოვარჯიშეები', 'Signed in, no role': 'შესული, როლის გარეშე',
  'Next step': 'შემდეგი ნაბიჯი',
  'Create a coach invite, send the link to a vetted coach, then let them invite their clients.': 'შექმენი მწვრთნელის მოწვევა, გაუგზავნე ბმული შემოწმებულ მწვრთნელს, მერე მან კლიენტები მოიწვიოს.',
  'New coach invite': 'ახალი მწვრთნელის მოწვევა',
  'Refresh': 'განახლება', 'Updated': 'განახლდა', 'Could not refresh': 'ვერ განახლდა',
  'paused': 'შეჩერებული',
  'No coaches yet.': 'მწვრთნელები ჯერ არ არიან.',
  'Coach invites': 'მწვრთნელის მოწვევები',
  'No open invites.': 'ღია მოწვევები არ არის.',
  'Coach name (for your list)': 'მწვრთნელის სახელი (შენი სიისთვის)',
  'e.g. Giorgi, Fitness One': 'მაგ. გიორგი, Fitness One',
  'Coach invite link': 'მწვრთნელის მოწვევის ბმული',
  'Welcome to the Tune Up beta! Open this link on your phone to set up your coach account: {link}': 'კეთილი იყოს შენი მობრძანება Tune Up-ის ბეტაში! მწვრთნელის ანგარიშის შესაქმნელად გახსენი ეს ბმული ტელეფონზე: {link}',
  'Works once, for 30 days. Send it to the coach only.': 'მუშაობს ერთხელ, 30 დღის განმავლობაში. გაუგზავნე მხოლოდ მწვრთნელს.',
  '{n} total': 'სულ {n}',
  'with {name}': '{name}-თან',
  'No users yet': 'მომხმარებლები ჯერ არ არიან',
  'Pairs': 'წყვილები',
  'Active since {date}': 'აქტიურია {date}-დან',
  'No pairs yet.': 'წყვილები ჯერ არ არის.',
  'Role': 'როლი', 'Consent': 'თანხმობა', 'Close': 'დახურვა',
  'Pause account': 'ანგარიშის შეჩერება', 'Un-pause account': 'ანგარიშის აღდგენა',
  'Account un-paused': 'ანგარიში აღდგა',
  'Could not change — try again': 'ვერ შეიცვალა — სცადე თავიდან'
};
