// Tune Up beta — Georgian strings, part 2 (week 3: logging, check-in, coach monitoring). Merged with ka.js in i18n.js.
export const KA2 = {
  // trainee logging
  'Today\'s log': 'დღევანდელი ჩანაწერი', 'This week': 'ეს კვირა', 'Mon–Sun': 'ორშ–კვი',
  'Food': 'კვება', 'Meal': 'კერძი', 'Add food': 'კვების დამატება', 'What': 'რა', 'e.g. chicken, rice, salad': 'მაგ. ქათამი, ბრინჯი, სალათი',
  'Add': 'დამატება', 'Enter calories or protein.': 'ჩაწერე კალორიები ან ცილა.',
  'goal': 'მიზანი', 'weigh-in': 'აწონვა', 'Weigh-in': 'აწონვა', 'Steps today': 'დღევანდელი ნაბიჯები',
  'Best in the morning, before breakfast.': 'საუკეთესოა დილით, საუზმემდე.', 'Clear': 'გასუფთავება', 'Enter a number.': 'ჩაწერე რიცხვი.',
  'Could not save — check the number': 'ვერ შეინახა — შეამოწმე რიცხვი',
  'Evening check-in': 'საღამოს შეფასება', 'How was your day? One tap and a line for your coach.': 'როგორი იყო დღე? ერთი შეხება და ერთი სტრიქონი მწვრთნელისთვის.',
  'How was your day?': 'როგორი იყო დღე?', 'A line for your coach (optional)': 'სტრიქონი მწვრთნელისთვის (არასავალდებულო)',
  'e.g. slept badly, knee felt fine': 'მაგ. ცუდად მეძინა, მუხლი კარგად იყო', 'Pick how your day was.': 'აირჩიე, როგორი იყო დღე.',
  'Saved — see you tomorrow': 'შენახულია — ხვალამდე',
  'Rough': 'ცუდი', 'Low': 'ასე-ისე', 'OK': 'ნორმალური', 'Good': 'კარგი', 'Great': 'შესანიშნავი',
  'Loading…': 'იტვირთება…', 'workout': 'ვარჯიში', 'rest': 'დასვენება', 'rest day': 'დასვენების დღე', 'Nothing logged': 'არაფერია ჩაწერილი', 'Nothing logged yet': 'ჯერ არაფერია ჩაწერილი',
  'Could not load — try again': 'ვერ ჩაიტვირთა — სცადე თავიდან',
  'Your weekly plan will appear here as soon as your coach sets it up. You can already log your day below.': 'კვირის გეგმა აქ გამოჩნდება, როგორც კი მწვრთნელი მოამზადებს. დღის ჩაწერა უკვე შეგიძლია ქვემოთ.',
  'e.g. Run 5 km without stopping': 'მაგ. 5 კმ სირბილი გაჩერების გარეშე',
  // coach monitoring
  'Needs your eye': 'ყურადღებას საჭიროებს', 'All quiet — nobody needs attention right now.': 'ყველაფერი წესრიგშია — ახლა არავის სჭირდება ყურადღება.',
  'Everyone today': 'ყველა დღეს', 'Missed workout': 'გამოტოვებული ვარჯიში', 'Low protein': 'ცოტა ცილა', 'yesterday': 'გუშინ',
  'Low mood': 'ცუდი განწყობა', 'Wrote a note': 'დაწერა შენიშვნა', 'Quiet': 'სიჩუმე', 'Last log {date}': 'ბოლო ჩანაწერი {date}',
  'Weight moved': 'წონა შეიცვალა', 'this week': 'ამ კვირაში',
  'Last 7 days': 'ბოლო 7 დღე', 'workouts done': 'შესრულებული ვარჯიში', 'avg': 'საშ.', 'protein avg': 'ცილა საშ.', 'steps avg': 'ნაბიჯი საშ.',
  'Check-ins': 'შეფასებები', 'Private notes': 'პირადი ჩანაწერები', 'only you see these': 'ამას მხოლოდ შენ ხედავ',
  'e.g. knee — avoid deep squats; check weight weekly': 'მაგ. მუხლი — ღრმა ჩაჯდომა არა; წონა ყოველკვირეულად', 'Save note': 'ჩანაწერის შენახვა',
  // week 4: chat, bell, sessions, feedback
  'Chat': 'ჩატი', 'You': 'შენ', 'No messages yet': 'შეტყობინებები ჯერ არ არის', 'Say hi': 'მიესალმე',
  'Questions, how a session went, a link to a form-check clip — it all goes here.': 'კითხვები, როგორ ჩაიარა ვარჯიშმა, ტექნიკის ვიდეოს ბმული — ყველაფერი აქ.',
  'Client': 'კლიენტი', 'Write a message': 'დაწერე შეტყობინება', 'Could not send — try again': 'ვერ გაიგზავნა — სცადე თავიდან',
  'Notifications': 'შეტყობინებები', 'Nothing yet — messages, sessions and check-ins will show up here.': 'ჯერ არაფერია — შეტყობინებები, სესიები და შეფასებები აქ გამოჩნდება.',
  'New session': 'ახალი სესია', 'Session cancelled': 'სესია გაუქმდა', 'Session moved': 'სესია გადაიწია',
  'Tell us what you think': 'გვითხარი შენი აზრი', 'What is confusing, missing or great? We read every note.': 'რა არის გაუგებარი, რა აკლია, რა მოგწონს? ყველა შენიშვნას ვკითხულობთ.',
  'Your note…': 'შენი შენიშვნა…', 'Send feedback': 'უკუკავშირის გაგზავნა', 'Thank you!': 'მადლობა!', 'What is confusing, missing or great?': 'რა არის გაუგებარი, რა აკლია, რა მოგწონს?',
  'Sessions': 'სესიები', 'Calendar': 'კალენდარი', 'Video call': 'ვიდეოზარი', 'Join': 'შეერთება', 'min': 'წთ', 'Cancelled': 'გაუქმებული', 'Moved': 'გადაწეული',
  'every {day}': 'ყოველ {day}', 'No sessions planned yet — your coach adds them here.': 'სესიები ჯერ არ არის დაგეგმილი — მწვრთნელი აქ დაამატებს.',
  'next 4 weeks': 'მომდევნო 4 კვირა', '{name} is usually available: {when}': '{name} ჩვეულებრივ თავისუფალია: {when}', 'Nothing planned': 'არაფერია დაგეგმილი',
  'Date': 'თარიღი', 'Time': 'დრო', 'Length': 'ხანგრძლივობა', 'Where': 'სად', 'Gym / in person': 'დარბაზი / პირისპირ', 'Place or video link': 'ადგილი ან ვიდეოს ბმული',
  'e.g. Fitness One, or https://meet.google.com/…': 'მაგ. Fitness One, ან https://meet.google.com/…', 'Repeat': 'გამეორება', 'One time': 'ერთხელ', 'Every week': 'ყოველ კვირას',
  'Note (optional)': 'შენიშვნა (არასავალდებულო)', 'e.g. bring your running shoes': 'მაგ. წამოიღე სარბენი ფეხსაცმელი', 'Add session': 'სესიის დამატება',
  'Pick a date and time.': 'აირჩიე თარიღი და დრო.', 'Paste the video link (starts with https://).': 'ჩასვი ვიდეოს ბმული (იწყება https://-ით).', 'Session added': 'სესია დაემატა',
  'Move to': 'გადატანა', 'Note to the client (optional)': 'შენიშვნა კლიენტს (არასავალდებულო)', 'e.g. gym closed that day': 'მაგ. დარბაზი იმ დღეს დაკეტილია',
  'Move': 'გადატანა', 'Cancel session': 'სესიის გაუქმება', 'Stop repeating after this one': 'ამის შემდეგ აღარ გამეორდეს',
  'Moved — the client is notified': 'გადაიწია — კლიენტს ეცნობა', 'Cancelled — the client is notified': 'გაუქმდა — კლიენტს ეცნობა',
  'Messages with {name}': 'მიმოწერა {name}-თან', 'When you are usually available': 'როდის ხარ ჩვეულებრივ თავისუფალი', 'e.g. Mon–Fri 8–20, Sat mornings': 'მაგ. ორშ–პარ 8–20, შაბათი დილით',
  // Tune (assistant)
  'Ask Tune': 'ჰკითხე Tune-ს', 'Your assistant': 'შენი ასისტენტი', 'about {name}': '{name}-ზე', 'Ask Tune about {name}': 'ჰკითხე Tune-ს {name}-ზე', 'How is the week going, what to watch': 'როგორ მიდის კვირა, რას მივაქციო ყურადღება',
  'Write to Tune': 'მისწერე Tune-ს', 'Tune is thinking…': 'Tune ფიქრობს…', 'Tune could not answer — try again': 'Tune-მა ვერ უპასუხა — სცადე თავიდან', 'Logged': 'ჩაიწერა',
  "Ask about today's workout, what is left to eat, or tell me what you ate — I will log it.": 'მკითხე დღევანდელ ვარჯიშზე, რა დაგრჩა საჭმელად, ან მითხარი, რა ჭამე — ჩავწერ.',
  'Ask who missed, what is on today, or how a client is doing.': 'მკითხე, ვინ გამოტოვა, რა არის დღეს, ან როგორ არის კლიენტი.',
  'Logs today': 'დღევანდელი ჩანაწერები', 'Feedback notes': 'უკუკავშირი', 'Feedback': 'უკუკავშირი', 'Nothing yet': 'ჯერ არაფერია'
};
